name: model-training-ev
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: s487197/ium:56
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train-ev model
        run: |
          python3 data.py
          python3 ium_train.py
          python3 ium_predict.py

          cat metrics.csv >> report.md
          cml-publish metrics_img.png --md >> report.md
          cml-send-comment report.md
        


          
          
          







